services:
  # 1. AUTH SERVICE (Golang + PostgreSQL)
  auth-service:
    build: ./auth-service
    ports: ["8081:8080"]
    env_file: ./auth-service/.env
    depends_on:
      - auth-db

  auth-db:
    image: postgres:13
    environment:
      POSTGRES_USER: user_auth
      POSTGRES_PASSWORD: pass_auth
      POSTGRES_DB: db_auth

  pgadmin: # Dashboard untuk PostgreSQL
    image: dpage/pgadmin4
    ports: ["8085:80"]
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@elapor.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - auth-db

  # 2. REPORT SERVICE (PHP + MySQL)
  report-service:
    build: ./report-service
    ports: ["8082:80"]
    env_file: ./report-service/.env
    depends_on:
      - report-db

  report-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_report

  phpmyadmin: # Dashboard untuk MySQL
    image: phpmyadmin/phpmyadmin
    ports: ["8080:80"]
    environment:
      PMA_HOST: report-db

  # 3. DISCUSSION SERVICE (Node.js + MongoDB)
  discussion-service:
    build: ./discussion-service
    ports: ["8083:3000"]
    env_file: ./discussion-service/.env
    depends_on:
      - discussion-db

  discussion-db:
    image: mongo:latest

  mongo-express: # Dashboard untuk MongoDB
    image: mongo-express
    ports: ["8086:8081"]
    environment:
      ME_CONFIG_MONGODB_SERVER: discussion-db
    depends_on:
      - discussion-db

  # 4. STATS SERVICE (Python + Redis)
  stats-service:
    build: ./stats-service
    ports: ["8084:5000"]
    env_file: ./stats-service/.env
    depends_on:
      - stats-db

  stats-db:
    image: redis:alpine

  redis-insight:
    image: redis/redisinsight:latest
    ports: ["8087:5540"]
    environment:
      - RI_PORT=5540
    depends_on:
      - stats-db
